swagger: '2.0'
info:
  description: Automatically produces natural language news reports on COVID-19.
  title: COVID-19 Reporter
  version: 1.0.0
paths:
  /health:
    options:
      description: "Returns the version number of the system as well. A reply indicates the system is healthy."
      responses:
        '200':
          description: OK
    get:
      description: "Returns the version number of the system as well. A reply indicates the system is healthy."
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - version
            properties:
              version:
                type: string
                example: "0.1.0"
  /languages:
    options:
      description: "Describes the available HTTP methods for this end point."
      responses:
        '200':
          description: OK
    get:
      description: Returns a JSON array of language codes supported by the /report endpoint.
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - languages
            properties:
              languages:
                type: array
                items:
                  type: string
                example:
                  - en
                  - fi
  /locations:
    options:
      description: "Describes the available HTTP methods for this end point."
      responses:
        '200':
          description: OK
    get:
      description: >-
        Query for valid locations supported by the /report endpoint
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              locations:
                type: array
                items:
                  type: string
                example:
                  - Finland
                  - Estonia
  /report:
    options:
      description: "Describes the available HTTP methods for this end point."
      responses:
        '200':
          description: OK
    post:
      description: Generate a report on the COVID-19 situation of a country
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: parameters
          schema:
            type: object
            required:
              - location
            properties:
              location:
                type: string
                example: "Finland"
              language:
                type: string
                example: "en"
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              language:
                type: string
                example: en
              header:
                type: string
                example: <h1>...</h1>
              body:
                type: string
                example: <p>...</p>
        '400':
          description: Missing or invalid inputs