from typing import Dict

COUNTRY_NAMES: Dict[str, Dict[str, str]] = {
    "fi": {
        "Afghanistan": "Afganistan",
        "Albania": "Albania",
        "Algeria": "Algeria",
        "Andorra": "Andorra",
        "Angola": "Angola",
        "Antigua and Barbuda": "Antigua ja Barbuda",
        "Argentina": "Argentiina",
        "Armenia": "Armenia",
        "Australia": "Australia",
        "Austria": "Itävalta",
        "Azerbaijan": "Azerbaidžan",
        "Bahamas": "Bahama",
        "Bahrain": "Bahrain",
        "Bangladesh": "Bangladesh",
        "Barbados": "Barbados",
        "Belarus": "Valko-Venäjä",
        "Belgium": "Belgia",
        "Belize": "Belize",
        "Benin": "Benin",
        "Bhutan": "Bhutan",
        "Bolivia": "Bolivia",
        "Bosnia and Herzegovina": "Bosnia ja Hertsegovina",
        "Botswana": "Botswana",
        "Brazil": "Brasilia",
        "Brunei": "Brunei",
        "Bulgaria": "Bulgaria",
        "Burkina Faso": "Burkina Faso",
        "Burundi": "Burundi",
        "Cambodia": "Kambodža",
        "Cameroon": "Kamerun",
        "Canada": "Kanada",
        "Cape Verde": "Kap Verde",
        "Central African Republic": "Keski-Afrikan tasavalta",
        "Chad": "Tšad",
        "Chile": "Chile",
        "China": "Kiina",
        "Colombia": "Kolumbia",
        "Comoros": "Komorit",
        "Costa Rica": "Costa Rica",
        "Côte d’Ivoire": "Norsunluurannikko",
        "Croatia": "Kroatia",
        "Cuba": "Kuuba",
        "Cyprus": "Kypros",
        "Czech Republic": "Tšekki",
        "Democratic Republic of the Congo": "Kongon demokraattinen tasavalta",
        "Denmark": "Tanska",
        "Djibouti": "Djibouti",
        "Dominica": "Dominica",
        "Dominican Republic": "Dominikaaninen tasavalta",
        "East Timor": "Itä-Timor",
        "Ecuador": "Ecuador",
        "Egypt": "Egypti",
        "El Salvador": "El Salvador",
        "Equatorial Guinea": "Päiväntasaajan Guinea",
        "Eritrea": "Eritrea",
        "Estonia": "Viro",
        "Ethiopia": "Etiopia",
        "Fiji": "Fidži",
        "Finland": "Suomi",
        "France": "Ranska",
        "Gabon": "Gabon",
        "Gambia": "Gambia",
        "Georgia": "Georgia",
        "Germany": "Saksa",
        "Ghana": "Ghana",
        "Greece": "Kreikka",
        "Grenada": "Grenada",
        "Guatemala": "Guatemala",
        "Guinea": "Guinea",
        "Guinea-Bissau": "Guinea-Bissau",
        "Guyana": "Guyana",
        "Haiti": "Haiti",
        "Honduras": "Honduras",
        "Hungary": "Unkari",
        "Iceland": "Islanti",
        "India": "Intia",
        "Indonesia": "Indonesia",
        "Iran": "Iran",
        "Iraq": "Irak",
        "Ireland": "Irlanti",
        "Israel": "Israel",
        "Italy": "Italia",
        "Jamaica": "Jamaika",
        "Japan": "Japani",
        "Jordan": "Jordan",
        "Kazakhstan": "Kazakstan",
        "Kenya": "Kenia",
        "Kiribati": "Kiribati",
        "Kuwait": "Kuwait",
        "Kyrgyzstan": "Kirgisia",
        "Laos": "Laos",
        "Latvia": "Latvia",
        "Lebanon": "Libanon",
        "Lesotho": "Lesotho",
        "Liberia": "Liberia",
        "Libya": "Libya",
        "Liechtenstein": "Liechtenstein",
        "Lithuania": "Liettua",
        "Luxembourg": "Luxemburg",
        "Madagascar": "Madagaskar",
        "Malawi": "Malawi",
        "Malaysia": "Malesia",
        "Maldives": "Malediivit",
        "Mali": "Mali",
        "Malta": "Malta",
        "Marshall Islands": "Marshallinsaaret",
        "Mauritania": "Mauritania",
        "Mauritius": "Mauritius",
        "Mexico": "Meksiko",
        "Micronesia": "Mikronesia",
        "Moldova": "Moldova",
        "Monaco": "Monaco",
        "Mongolia": "Mongolia",
        "Montenegro": "Montenegro",
        "Morocco": "Marokko",
        "Mozambique": "Mosambik",
        "Myanmar": "Myanmar",
        "Namibia": "Namibia",
        "Nauru": "Nauru",
        "Nepal": "Nepal",
        "Netherlands": "Alankomaat",
        "New Zealand": "Uusi-Seelanti",
        "Nicaragua": "Nicaragua",
        "Niger": "Niger",
        "Nigeria": "Nigeria",
        "North Korea": "Pohjois-Korea",
        "Norway": "Norja",
        "Oman": "Oman",
        "Pakistan": "Pakistan",
        "Palau": "Palau",
        "Panama": "Panama",
        "Papua New Guinea": "Papua-Uusi-Guinea",
        "Paraguay": "Paraguay",
        "Peru": "Peru",
        "Philippines": "Filippiinit",
        "Poland": "Puola",
        "Portugal": "Portugali",
        "Qatar": "Qatar",
        "Republic of the Congo": "Kongon tasavalta",
        "Republic of Macedonia": "Makedonia",
        "Romania": "Romania",
        "Russia": "Venäj",
        "Rwanda": "Ruanda",
        "Saint Kitts and Nevis": "Saint Kitts ja Nevis",
        "Saint Lucia": "Saint Lucia",
        "Saint Vincent and the Grenadines": "Saint Vincent ja Grenadiinit",
        "Samoa": "Samoa",
        "San Marino": "San Marino",
        "Sao Tome and Principe": "São Tomé ja Príncipe",
        "Saudi Arabia": "Saudi-Arabia",
        "Senegal": "Senegal",
        "Serbia": "Serbia",
        "Seychelles": "Seychellit",
        "Sierra Leone": "Sierra Leone",
        "Singapore": "Singapore",
        "Slovakia": "Slovakia",
        "Slovenia": "Slovenia",
        "Solomon Islands": "Salomonsaaret",
        "Somalia": "Somalia",
        "South Africa": "Etelä-Afrikka",
        "South Korea": "Etelä-Korea",
        "South Sudan": "Etelä-Sudan",
        "Spain": "Espanja",
        "Sri Lanka": "Sri Lanka",
        "Sudan": "Sudan",
        "Suriname": "Suriname",
        "Swaziland": "Swazimaa",
        "Sweden": "Ruotsi",
        "Switzerland": "Sveitsi",
        "Syria": "Syyria",
        "Tajikistan": "Tadžikistan",
        "Tanzania": "Tansania",
        "Thailand": "Thaimaa",
        "Togo": "Togo",
        "Tonga": "Tonga",
        "Trinidad and Tobago": "Trinidad ja Tobago",
        "Tunisia": "Tunisia",
        "Turkey": "Turkki",
        "Turkmenistan": "Turkmenistan",
        "Tuvalu": "Tuvalu",
        "Uganda": "Uganda",
        "Ukraine": "Ukraina",
        "United Arab Emirates": "Yhdistyneet arabiemiirikunnat",
        "United Kingdom": "Yhdistynyt kuningaskunta",
        "United States of America": "Yhdysvallat",
        "Uruguay": "Uruguay",
        "Uzbekistan": "Uzbekistan",
        "Vanuatu": "Vanuatu",
        "Venezuela": "Venezuela",
        "Vietnam": "Vietnam",
        "Yemen": "Jemen",
        "Zambia": "Sambia",
        "Zimbabwe": "Zimbabwe",
    },
    "en": {
        "Afghanistan": "Afghanistan",
        "Albania": "Albania",
        "Algeria": "Algeria",
        "Andorra": "Andorra",
        "Angola": "Angola",
        "Antigua and Barbuda": "Antigua and Barbuda",
        "Argentina": "Argentina",
        "Armenia": "Armenia",
        "Australia": "Australia",
        "Austria": "Austria",
        "Azerbaijan": "Azerbaijan",
        "Bahamas": "Bahamas",
        "Bahrain": "Bahrain",
        "Bangladesh": "Bangladesh",
        "Barbados": "Barbados",
        "Belarus": "Belarus",
        "Belgium": "Belgium",
        "Belize": "Belize",
        "Benin": "Benin",
        "Bhutan": "Bhutan",
        "Bolivia": "Bolivia",
        "Bosnia and Herzegovina": "Bosnia and Herzegovina",
        "Botswana": "Botswana",
        "Brazil": "Brazil",
        "Brunei": "Brunei",
        "Bulgaria": "Bulgaria",
        "Burkina Faso": "Burkina Faso",
        "Burundi": "Burundi",
        "Cambodia": "Cambodia",
        "Cameroon": "Cameroon",
        "Canada": "Canada",
        "Cape Verde": "Cape Verde",
        "Central African Republic": "Central African Republic",
        "Chad": "Chad",
        "Chile": "Chile",
        "China": "China",
        "Colombia": "Colombia",
        "Comoros": "Comoros",
        "Costa Rica": "Costa Rica",
        "Côte d’Ivoire": "Côte d’Ivoire",
        "Croatia": "Croatia",
        "Cuba": "Cuba",
        "Cyprus": "Cyprus",
        "Czech Republic": "Czech Republic",
        "Democratic Republic of the Congo": "Democratic Republic of the Congo",
        "Denmark": "Denmark",
        "Djibouti": "Djibouti",
        "Dominica": "Dominica",
        "Dominican Republic": "Dominican Republic",
        "East Timor": "East Timor",
        "Ecuador": "Ecuador",
        "Egypt": "Egypt",
        "El Salvador": "El Salvador",
        "Equatorial Guinea": "Equatorial Guinea",
        "Eritrea": "Eritrea",
        "Estonia": "Estonia",
        "Ethiopia": "Ethiopia",
        "Fiji": "Fiji",
        "Finland": "Finland",
        "France": "France",
        "Gabon": "Gabon",
        "Gambia": "Gambia",
        "Georgia": "Georgia",
        "Germany": "Germany",
        "Ghana": "Ghana",
        "Greece": "Greece",
        "Grenada": "Grenada",
        "Guatemala": "Guatemala",
        "Guinea": "Guinea",
        "Guinea-Bissau": "Guinea-Bissau",
        "Guyana": "Guyana",
        "Haiti": "Haiti",
        "Honduras": "Honduras",
        "Hungary": "Hungary",
        "Iceland": "Iceland",
        "India": "India",
        "Indonesia": "Indonesia",
        "Iran": "Iran",
        "Iraq": "Iraq",
        "Ireland": "Ireland",
        "Israel": "Israel",
        "Italy": "Italy",
        "Jamaica": "Jamaica",
        "Japan": "Japan",
        "Jordan": "Jordan",
        "Kazakhstan": "Kazakhstan",
        "Kenya": "Kenya",
        "Kiribati": "Kiribati",
        "Kuwait": "Kuwait",
        "Kyrgyzstan": "Kyrgyzstan",
        "Laos": "Laos",
        "Latvia": "Latvia",
        "Lebanon": "Lebanon",
        "Lesotho": "Lesotho",
        "Liberia": "Liberia",
        "Libya": "Libya",
        "Liechtenstein": "Liechtenstein",
        "Lithuania": "Lithuania",
        "Luxembourg": "Luxembourg",
        "Madagascar": "Madagascar",
        "Malawi": "Malawi",
        "Malaysia": "Malaysia",
        "Maldives": "Maldives",
        "Mali": "Mali",
        "Malta": "Malta",
        "Marshall Islands": "Marshall Islands",
        "Mauritania": "Mauritania",
        "Mauritius": "Mauritius",
        "Mexico": "Mexico",
        "Micronesia": "Micronesia",
        "Moldova": "Moldova",
        "Monaco": "Monaco",
        "Mongolia": "Mongolia",
        "Montenegro": "Montenegro",
        "Morocco": "Morocco",
        "Mozambique": "Mozambique",
        "Myanmar": "Myanmar",
        "Namibia": "Namibia",
        "Nauru": "Nauru",
        "Nepal": "Nepal",
        "Netherlands": "Netherlands",
        "New Zealand": "New Zealand",
        "Nicaragua": "Nicaragua",
        "Niger": "Niger",
        "Nigeria": "Nigeria",
        "North Korea": "North Korea",
        "Norway": "Norway",
        "Oman": "Oman",
        "Pakistan": "Pakistan",
        "Palau": "Palau",
        "Panama": "Panama",
        "Papua New Guinea": "Papua New Guinea",
        "Paraguay": "Paraguay",
        "Peru": "Peru",
        "Philippines": "Philippines",
        "Poland": "Poland",
        "Portugal": "Portugal",
        "Qatar": "Qatar",
        "Republic of the Congo": "Republic of the Congo",
        "Republic of Macedonia": "Republic of Macedonia",
        "Romania": "Romania",
        "Russia": "Russia",
        "Rwanda": "Rwanda",
        "Saint Kitts and Nevis": "Saint Kitts and Nevis",
        "Saint Lucia": "Saint Lucia",
        "Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines",
        "Samoa": "Samoa",
        "San Marino": "San Marino",
        "Sao Tome and Principe": "Sao Tome and Principe",
        "Saudi Arabia": "Saudi Arabia",
        "Senegal": "Senegal",
        "Serbia": "Serbia",
        "Seychelles": "Seychelles",
        "Sierra Leone": "Sierra Leone",
        "Singapore": "Singapore",
        "Slovakia": "Slovakia",
        "Slovenia": "Slovenia",
        "Solomon Islands": "Solomon Islands",
        "Somalia": "Somalia",
        "South Africa": "South Africa",
        "South Korea": "South Korea",
        "South Sudan": "South Sudan",
        "Spain": "Spain",
        "Sri Lanka": "Sri Lanka",
        "Sudan": "Sudan",
        "Suriname": "Suriname",
        "Swaziland": "Swaziland",
        "Sweden": "Sweden",
        "Switzerland": "Switzerland",
        "Syria": "Syria",
        "Tajikistan": "Tajikistan",
        "Tanzania": "Tanzania",
        "Thailand": "Thailand",
        "Togo": "Togo",
        "Tonga": "Tonga",
        "Trinidad and Tobago": "Trinidad and Tobago",
        "Tunisia": "Tunisia",
        "Turkey": "Turkey",
        "Turkmenistan": "Turkmenistan",
        "Tuvalu": "Tuvalu",
        "Uganda": "Uganda",
        "Ukraine": "Ukraine",
        "United Arab Emirates": "United Arab Emirates",
        "United Kingdom": "United Kingdom",
        "United States of America": "United States of America",
        "Uruguay": "Uruguay",
        "Uzbekistan": "Uzbekistan",
        "Vanuatu": "Vanuatu",
        "Venezuela": "Venezuela",
        "Vietnam": "Vietnam",
        "Yemen": "Yemen",
        "Zambia": "Zambia",
        "Zimbabwe": "Zimbabwe",
    },
}
